# Generated by Django 5.0.6 on 2024-08-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('Department_Name', models.CharField(max_length=100)),
                ('Employees', models.CharField(choices=[('BioOne(EB-49)', 'BioOne(EB-49)'), ('ChikU(EN-1089)', 'ChikU(EN-1089)'), ('CVCV(EB-42)', 'CVCV(EB-42)'), ('Daily Allow(EB-39)', 'Daily Allow(EB-39)'), ('Daily Half(EB-52)', 'Daily Half(EB-52)'), ('Daily Mon(EB-3)', 'Daily Mon(EB-3)'), ('Day Count(EB-36)', 'Day Count(EB-36)')], max_length=20)),
            ],
        ),
    ]
