# Generated by Django 5.0.6 on 2024-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0005_claimapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, unique=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='photographs/')),
                ('project_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Customer Service', 'Customer Service'), ('Legal', 'Legal'), ('R&D', 'Research and Development'), ('Admin', 'Administration')], max_length=100)),
                ('group', models.CharField(choices=[('Tester', 'A'), ('B', 'Developer'), ('C', 'Manager'), ('D', 'Teamlead'), ('E', 'Employee'), ('F', 'Fresher'), ('G', 'Experienced'), ('H', 'Python'), ('I', 'Java'), ('J', 'Web Developing')], max_length=100)),
                ('employee', models.CharField(choices=[('John Doe', 'John Doe'), ('Jane Smith', 'Jane Smith'), ('Alice Johnson', 'Alice Johnson'), ('Bob Brown', 'Bob Brown'), ('Charlie Davis', 'Charlie Davis'), ('Diana Evans', 'Diana Evans'), ('Frank Green', 'Frank Green'), ('Grace Harris', 'Grace Harris'), ('Henry Ives', 'Henry Ives'), ('Ivy Jones', 'Ivy Jones')], max_length=100)),
                ('shift', models.CharField(choices=[('Morning', 'Morning Shift'), ('Afternoon', 'Afternoon Shift'), ('Night', 'Night Shift'), ('Weekend', 'Weekend Shift'), ('Flexible', 'Flexible Shift')], max_length=100)),
                ('supervisor', models.CharField(choices=[('John Smith', 'John Smith'), ('Emily Johnson', 'Emily Johnson'), ('Michael Brown', 'Michael Brown'), ('Sarah Davis', 'Sarah Davis'), ('David Wilson', 'David Wilson'), ('Laura Moore', 'Laura Moore'), ('James Taylor', 'James Taylor'), ('Linda Anderson', 'Linda Anderson'), ('Robert Thomas', 'Robert Thomas'), ('Karen White', 'Karen White')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('public_holiday', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('rest_day', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
            ],
        ),
    ]
