# Generated by Django 5.0.6 on 2024-08-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=10, unique=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='photographs/')),
                ('group_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Customer Service', 'Customer Service'), ('Legal', 'Legal'), ('R&D', 'Research and Development'), ('Admin', 'Administration')], max_length=100)),
                ('projects', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Operations', 'Operations'), ('Customer Service', 'Customer Service'), ('Legal', 'Legal'), ('R&D', 'Research and Development'), ('Admin', 'Administration')], max_length=100)),
                ('employees', models.CharField(choices=[('John Doe', 'John Doe'), ('Jane Smith', 'Jane Smith'), ('Alice Johnson', 'Alice Johnson'), ('Bob Brown', 'Bob Brown'), ('Charlie Davis', 'Charlie Davis'), ('Diana Evans', 'Diana Evans'), ('Frank Green', 'Frank Green'), ('Grace Harris', 'Grace Harris'), ('Henry Ives', 'Henry Ives'), ('Ivy Jones', 'Ivy Jones')], max_length=100)),
            ],
        ),
    ]
