# Generated by Django 5.0.6 on 2024-08-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0007_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(choices=[('Demo cost center Testing-dc_123', 'Demo cost center Testing-dc_123'), ('Human Resources-HRs', 'Human Resources-HRs'), ('Project A s123@-PAs@85', 'Project A s123@-PAs@85'), ('Project B-PB', 'Project B-PB')], max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
