# Generated by Django 5.0.6 on 2024-08-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0008_costcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=5, max_digits=65)),
                ('Issue_Date', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
