# Generated by Django 5.0.6 on 2024-09-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0009_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Attachment', models.ImageField(blank=True, null=True, upload_to='photographs/')),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Of_Issue', models.DateField()),
                ('Date_Of_Collection', models.DateField()),
            ],
        ),
    ]
