# Generated by Django 5.0.6 on 2024-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0010_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification', models.CharField(max_length=100)),
                ('Grade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Attachment', models.ImageField(blank=True, null=True, upload_to='photographs/')),
                ('Effective_Date', models.DateField()),
                ('Projected_Date', models.DateField()),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
