# Generated by Django 5.0.6 on 2024-09-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0011_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
    ]
