# Generated by Django 5.0.6 on 2024-09-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0012_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Leave_type_title', models.CharField(max_length=100)),
                ('Leave_code', models.CharField(max_length=100)),
                ('Functionality', models.CharField(choices=[('Apply in days', 'Apply in days'), ('Apply in hours', 'Apply in hours'), ('Apply in minutes', 'Apply in minutes'), ('Off in lieu', 'Off in lieu'), ('No pay leave', 'No pay leave')], max_length=40)),
                ('No_of_default_leave', models.IntegerField()),
                ('Full_day', models.BooleanField(default=False)),
                ('Half_day', models.BooleanField(default=False)),
                ('Employee_remarks', models.BooleanField(default=False)),
                ('Upload_document', models.BooleanField(default=False)),
                ('Approvers_remarks', models.BooleanField(default=False)),
                ('Entitled_in_probation', models.BooleanField(default=False)),
                ('Not_entitled_in_probation', models.BooleanField(default=False)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Yes', models.BooleanField(default=False)),
                ('No', models.BooleanField(default=False)),
            ],
        ),
    ]
