# Generated by Django 5.0.6 on 2024-09-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0013_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=100)),
                ('Shift', models.CharField(max_length=100)),
                ('Employee', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('In_Time', models.TimeField()),
                ('Out_Time', models.TimeField()),
            ],
        ),
    ]
