# Generated by Django 5.0.6 on 2024-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0014_atimesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(choices=[('Employees Leave Information', 'Employees Leave Information'), ('Employees Annual Earned Leave Information', 'Employees Annual Earned Leave Information')], max_length=100)),
                ('Format', models.CharField(choices=[('Excel', 'Excel')], max_length=100)),
                ('Upload_document', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
