# Generated by Django 5.0.6 on 2024-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0015_bulkupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffinLieuAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template', models.CharField(choices=[('Template', 'Template')], max_length=100)),
                ('Format', models.CharField(choices=[('Excel', 'Excel')], max_length=100)),
                ('Upload_document', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='Upload_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
