# Generated by Django 5.0.6 on 2024-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0016_offinlieuallocation_alter_bulkupload_upload_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_xls_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
