# Generated by Django 5.0.6 on 2024-09-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0017_claimupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roster_Name', models.CharField(max_length=100)),
                ('Select_Days', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('Roster_From_Period', models.DateField()),
                ('Roster_To_Period', models.DateField()),
                ('In_Time', models.TimeField()),
                ('Out_Time', models.TimeField()),
                ('Earliest_Clock_In_Time', models.TimeField()),
                ('Last_Clock_Out_Time', models.TimeField()),
                ('Auto_Clock_Out', models.BooleanField(default=False)),
                ('Break_Time_Normal_Hours', models.DurationField()),
                ('OT_Break_Time_Normal_Hours', models.DurationField()),
                ('OT_To_Only_Start_After', models.DurationField()),
                ('OT_Break_Takes_Effect_After', models.DurationField()),
                ('Late_In_From', models.TimeField()),
                ('Apply_Days', models.CharField(max_length=100)),
                ('Basic_Pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Custom_Fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fixed', models.BooleanField(default=False)),
                ('Common_OT', models.BooleanField(default=False)),
                ('Hourly_OT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_OT_Hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Off_in_Lieu', models.BooleanField(default=False)),
                ('Default', models.BooleanField(default=False)),
                ('MOM_Regulation', models.BooleanField(default=False)),
                ('OT_By_Minutes', models.IntegerField()),
                ('OT_By_Block_30mins', models.BooleanField(default=False)),
                ('OT_By_Block_15mins', models.BooleanField(default=False)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.employee')),
                ('Groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.groups')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.project')),
            ],
        ),
    ]
