# Generated by Django 5.0.6 on 2024-09-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0019_importanttimesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewShifts',
            fields=[
                ('Shift_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Shift_Name', models.CharField(max_length=100)),
                ('Pick_Color', models.CharField(max_length=7)),
                ('In_Time', models.TimeField()),
                ('Out_Time', models.TimeField()),
                ('Earliest_Clock_In_Time', models.TimeField()),
                ('Last_Clock_Out_Time', models.TimeField()),
                ('Auto_Clock_Out', models.BooleanField(default=False)),
                ('Break_Time_Normal_Hours', models.DurationField()),
                ('OT_Break_Time_Normal_Hours', models.DurationField()),
                ('OT_To_Only_Start_After', models.DurationField()),
                ('OT_Break_Takes_Effect_After', models.DurationField()),
                ('Late_In_From', models.TimeField()),
                ('Apply_Days', models.CharField(max_length=100)),
                ('Basic_Pay', models.BooleanField(default=False)),
                ('Custom_Fine', models.BooleanField(default=False)),
                ('Fixed', models.BooleanField(default=False)),
                ('Roster_Settings', models.BooleanField(default=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Postal_Code', models.CharField(max_length=10)),
                ('Supervisor_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
