# Generated by Django 5.0.6 on 2024-09-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0020_addnewshifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workflow_Type', models.CharField(max_length=150)),
                ('Default', models.BooleanField(default=False)),
                ('Specific', models.BooleanField(default=False)),
                ('Workflow_Name', models.CharField(max_length=100)),
                ('Levels', models.IntegerField()),
                ('Departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.employee')),
                ('Groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.groups')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapp.project')),
            ],
        ),
    ]
